# This rule is not used by the project fathom itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over fathom.skaphos.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fathom
    app.kubernetes.io/managed-by: kustomize
  name: nodecertificatecheck-admin-role
rules:
- apiGroups:
  - fathom.skaphos.io
  resources:
  - nodecertificatechecks
  verbs:
  - '*'
- apiGroups:
  - fathom.skaphos.io
  resources:
  - nodecertificatechecks/status
  verbs:
  - get
