---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fathom.skaphos.io
  resources:
  - addonchecks
  - clusterhealths
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fathom.skaphos.io
  resources:
  - addonchecks/finalizers
  - clusterhealths/finalizers
  - healthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - fathom.skaphos.io
  resources:
  - addonchecks/status
  - clusterhealths/status
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fathom.skaphos.io
  resources:
  - healthreports
  verbs:
  - create
  - get
  - list
  - watch
