---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fathom.skaphos.io
  resources:
  - addonchecks
  - clusterhealths
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fathom.skaphos.io
  resources:
  - addonchecks/finalizers
  - clusterhealths/finalizers
  - healthchecks/finalizers
  - nodecertificatechecks/finalizers
  verbs:
  - update
- apiGroups:
  - fathom.skaphos.io
  resources:
  - addonchecks/status
  - clusterhealths/status
  - healthchecks/status
  - nodecertificatechecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fathom.skaphos.io
  resources:
  - healthreports
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - fathom.skaphos.io
  resources:
  - nodecertificatechecks
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
