/*
SPDX-FileCopyrightText: 2026 Skaphos
SPDX-License-Identifier: MIT
*/

// Package rbacgen materializes each addon adapter's declared least-privilege
// RBAC (adapter.RBACDeclarer) into deployable artifacts: a per-addon
// ServiceAccount + read-only ClusterRole + ClusterRoleBinding under
// config/rbac/addons/, a namespaced Role granting the operator only
// `impersonate` on those ServiceAccounts, a Helm data file, and a docs matrix.
//
// It is the build-time half of SKA-58: the reconciler impersonates the per-addon
// ServiceAccount at run time so an adapter's blast radius is exactly its declared
// rules. Generation is committed and gated by `verify-generated`; the read-only
// guard (guard_test.go) fails any write verb not justified by a
// adapter.PolicyRule.WriteReason.
package rbacgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"

	"github.com/skaphos/fathom/pkg/adapter"
)

// Fixed names/namespaces. These are the kustomize *base* names (before the
// config/default namePrefix "fathom-" and namespace "fathom-system" rewrite
// them). The reconciler never hard-codes the deployed name — it resolves the
// ServiceAccount by adapter.AddonLabel — so only the impersonate Role's
// resourceNames must track the rename, which config/rbac/addons/kustomizeconfig.yaml
// teaches kustomize to do.
const (
	baseNamespace      = "system"
	managerSAName      = "controller-manager"
	impersonatorName   = "addon-impersonator"
	addonsKustomizeDir = "config/rbac/addons"
	docsMatrixPath     = "docs/reference/rbac.md"
	helmDataPath       = "deploy/helm/fathom-operator/files/addon-rbac.yaml"
	generatedByComment = "# Generated by internal/adapter/rbacgen. DO NOT EDIT.\n" +
		"# Regenerate with `go -C tools tool task gen:addon-rbac`.\n"
	generatedByMarkdown = "<!-- Generated by internal/adapter/rbacgen. DO NOT EDIT. " +
		"Regenerate with `go -C tools tool task gen:addon-rbac`. -->\n"
)

// AddonRBAC is one addon's RBAC input, resolved from its adapter.
type AddonRBAC struct {
	// Addon is the adapter identity (adapter.Adapter.Name).
	Addon string
	// ServiceAccount is the base ServiceAccount name (pre-namePrefix).
	ServiceAccount string
	// Rules are the adapter's declared least-privilege grants. Nil when the
	// adapter does not implement adapter.RBACDeclarer.
	Rules []adapter.PolicyRule
}

// Collect resolves the per-addon RBAC for adapters, deduped by adapter Name and
// sorted by addon name for deterministic output. An adapter that does not
// implement adapter.RBACDeclarer yields an entry with nil Rules so callers can
// flag the omission rather than silently generating an empty role.
func Collect(adapters []adapter.Adapter) []AddonRBAC {
	seen := map[string]bool{}
	out := make([]AddonRBAC, 0, len(adapters))
	for _, a := range adapters {
		name := a.Name()
		if seen[name] {
			continue
		}
		seen[name] = true
		var rules []adapter.PolicyRule
		if d, ok := a.(adapter.RBACDeclarer); ok {
			rules = d.RBACRules()
		}
		out = append(out, AddonRBAC{
			Addon:          name,
			ServiceAccount: adapter.AddonServiceAccountName(name),
			Rules:          rules,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Addon < out[j].Addon })
	return out
}

// UnjustifiedWrites returns a human-readable message for every grant that would
// fail the read-only guard: a write verb (anything but get/list/watch) on a rule
// with no adapter.PolicyRule.WriteReason, or an addon that declared no rules at
// all. An empty result means every addon is read-only except for writes that
// document why they exist. It is the single security predicate the guard enforces.
func UnjustifiedWrites(addons []AddonRBAC) []string {
	var violations []string
	for _, a := range addons {
		if len(a.Rules) == 0 {
			violations = append(violations, fmt.Sprintf("addon %q declares no RBAC rules (missing adapter.RBACDeclarer?)", a.Addon))
			continue
		}
		for _, r := range a.Rules {
			for _, v := range r.Verbs {
				if adapter.IsReadVerb(v) || r.WriteReason != "" {
					continue
				}
				violations = append(violations, fmt.Sprintf("addon %q: write verb %q on %v has no WriteReason", a.Addon, v, r.Resources))
			}
		}
	}
	return violations
}

// Files returns every generated artifact as a repo-relative path -> content map,
// or an error if any adapter declared no rules (adapter.RBACDeclarer omitted).
func Files(addons []AddonRBAC) (map[string][]byte, error) {
	for _, a := range addons {
		if len(a.Rules) == 0 {
			return nil, fmt.Errorf("rbacgen: adapter %q declares no RBAC rules (does it implement adapter.RBACDeclarer?)", a.Addon)
		}
	}
	files := map[string][]byte{}

	// Per-addon ServiceAccount + ClusterRole + ClusterRoleBinding.
	resources := make([]string, 0, len(addons)+1)
	for _, a := range addons {
		body, err := renderAddon(a)
		if err != nil {
			return nil, err
		}
		fname := "addon-" + a.Addon + ".yaml"
		files[filepath.Join(addonsKustomizeDir, fname)] = body
		resources = append(resources, fname)
	}

	// Operator impersonate Role + RoleBinding.
	imp, err := renderImpersonator(addons)
	if err != nil {
		return nil, err
	}
	files[filepath.Join(addonsKustomizeDir, "operator-impersonate.yaml")] = imp
	resources = append(resources, "operator-impersonate.yaml")

	files[filepath.Join(addonsKustomizeDir, "kustomization.yaml")] = renderKustomization(resources)
	files[filepath.Join(addonsKustomizeDir, "kustomizeconfig.yaml")] = []byte(kustomizeConfig)
	files[helmDataPath] = renderHelmData(addons)
	files[docsMatrixPath] = renderDocs(addons)
	return files, nil
}

// Write generates every artifact and writes it under root. Returns the sorted
// list of repo-relative paths written. It also prunes stale per-addon manifests:
// a removed or renamed adapter's addon-<name>.yaml would otherwise linger as an
// unreferenced tracked file (the regenerated kustomization no longer lists it, so
// it is never deployed — but it clutters the tree and, for a read-only removed
// adapter, slips past the read-only guard). Any addon-*.yaml not in the new set
// is removed.
func Write(root string, adapters []adapter.Adapter) ([]string, error) {
	files, err := Files(Collect(adapters))
	if err != nil {
		return nil, err
	}

	stale, err := filepath.Glob(filepath.Join(root, addonsKustomizeDir, "addon-*.yaml"))
	if err != nil {
		return nil, err
	}
	for _, m := range stale {
		rel := filepath.Join(addonsKustomizeDir, filepath.Base(m))
		if _, keep := files[rel]; !keep {
			if err := os.Remove(m); err != nil {
				return nil, err
			}
		}
	}

	paths := make([]string, 0, len(files))
	for rel, body := range files {
		abs := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(abs, body, 0o644); err != nil {
			return nil, err
		}
		paths = append(paths, rel)
	}
	sort.Strings(paths)
	return paths, nil
}

// --- YAML-friendly minimal object model (clean, deterministic output) ---

type k8sObject struct {
	APIVersion string       `json:"apiVersion"`
	Kind       string       `json:"kind"`
	Metadata   objectMeta   `json:"metadata"`
	Rules      []policyRule `json:"rules,omitempty"`
	RoleRef    *roleRef     `json:"roleRef,omitempty"`
	Subjects   []subject    `json:"subjects,omitempty"`
}

type objectMeta struct {
	Name      string            `json:"name"`
	Namespace string            `json:"namespace,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
}

type policyRule struct {
	APIGroups     []string `json:"apiGroups"`
	Resources     []string `json:"resources"`
	Verbs         []string `json:"verbs"`
	ResourceNames []string `json:"resourceNames,omitempty"`
}

type roleRef struct {
	APIGroup string `json:"apiGroup"`
	Kind     string `json:"kind"`
	Name     string `json:"name"`
}

type subject struct {
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}

func stdLabels(extra map[string]string) map[string]string {
	m := map[string]string{
		"app.kubernetes.io/name":       "fathom",
		"app.kubernetes.io/managed-by": "kustomize",
	}
	for k, v := range extra {
		m[k] = v
	}
	return m
}

// clusterRules converts declared PolicyRules into rendered rbac rules, dropping
// the WriteReason (not an RBAC field — it lives only in the model, the guard, and
// the docs matrix).
func clusterRules(rules []adapter.PolicyRule) []policyRule {
	out := make([]policyRule, len(rules))
	for i, r := range rules {
		out[i] = policyRule{APIGroups: r.APIGroups, Resources: r.Resources, Verbs: r.Verbs}
	}
	return out
}

func renderAddon(a AddonRBAC) ([]byte, error) {
	sa := k8sObject{
		APIVersion: "v1",
		Kind:       "ServiceAccount",
		Metadata: objectMeta{
			Name:      a.ServiceAccount,
			Namespace: baseNamespace,
			Labels:    stdLabels(map[string]string{adapter.AddonLabel: a.Addon}),
		},
	}
	cr := k8sObject{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "ClusterRole",
		Metadata:   objectMeta{Name: a.ServiceAccount, Labels: stdLabels(map[string]string{adapter.AddonLabel: a.Addon})},
		Rules:      clusterRules(a.Rules),
	}
	crb := k8sObject{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "ClusterRoleBinding",
		Metadata:   objectMeta{Name: a.ServiceAccount, Labels: stdLabels(map[string]string{adapter.AddonLabel: a.Addon})},
		RoleRef:    &roleRef{APIGroup: "rbac.authorization.k8s.io", Kind: "ClusterRole", Name: a.ServiceAccount},
		Subjects:   []subject{{Kind: "ServiceAccount", Name: a.ServiceAccount, Namespace: baseNamespace}},
	}
	return marshalDocs(generatedByComment, sa, cr, crb)
}

func renderImpersonator(addons []AddonRBAC) ([]byte, error) {
	names := make([]string, len(addons))
	for i, a := range addons {
		names[i] = a.ServiceAccount
	}
	sort.Strings(names)
	role := k8sObject{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "Role",
		Metadata:   objectMeta{Name: impersonatorName, Namespace: baseNamespace, Labels: stdLabels(nil)},
		// SA impersonation is a namespaced authorization check on the
		// `serviceaccounts` resource, so a namespaced Role scoped by resourceNames
		// grants the operator the tightest possible impersonate: only these named
		// ServiceAccounts, and only in fathom-system.
		Rules: []policyRule{{
			APIGroups:     []string{""},
			Resources:     []string{"serviceaccounts"},
			Verbs:         []string{"impersonate"},
			ResourceNames: names,
		}},
	}
	rb := k8sObject{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "RoleBinding",
		Metadata:   objectMeta{Name: impersonatorName, Namespace: baseNamespace, Labels: stdLabels(nil)},
		RoleRef:    &roleRef{APIGroup: "rbac.authorization.k8s.io", Kind: "Role", Name: impersonatorName},
		Subjects:   []subject{{Kind: "ServiceAccount", Name: managerSAName, Namespace: baseNamespace}},
	}
	return marshalDocs(generatedByComment, role, rb)
}

func marshalDocs(header string, objs ...k8sObject) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	for i, o := range objs {
		if i > 0 {
			buf.WriteString("---\n")
		}
		b, err := yaml.Marshal(o)
		if err != nil {
			return nil, err
		}
		buf.Write(b)
	}
	return buf.Bytes(), nil
}

func renderKustomization(resources []string) []byte {
	var buf bytes.Buffer
	buf.WriteString(generatedByComment)
	buf.WriteString("apiVersion: kustomize.config.k8s.io/v1beta1\n")
	buf.WriteString("kind: Kustomization\n")
	buf.WriteString("resources:\n")
	for _, r := range resources {
		fmt.Fprintf(&buf, "- %s\n", r)
	}
	buf.WriteString("configurations:\n")
	buf.WriteString("- kustomizeconfig.yaml\n")
	return buf.Bytes()
}

// kustomizeConfig teaches kustomize's name-reference transformer to rewrite the
// impersonate Role's resourceNames when config/default's namePrefix renames the
// per-addon ServiceAccounts (kustomize does not track resourceNames by default),
// keeping the impersonate grant scoped to the real deployed SA names.
const kustomizeConfig = generatedByComment +
	`nameReference:
- kind: ServiceAccount
  version: v1
  fieldSpecs:
  - path: rules/resourceNames
    kind: Role
`

func renderHelmData(addons []AddonRBAC) []byte {
	type helmRule struct {
		APIGroups []string `json:"apiGroups"`
		Resources []string `json:"resources"`
		Verbs     []string `json:"verbs"`
	}
	type helmAddon struct {
		Name  string     `json:"name"`
		Rules []helmRule `json:"rules"`
	}
	data := struct {
		Addons []helmAddon `json:"addons"`
	}{}
	for _, a := range addons {
		ha := helmAddon{Name: a.Addon}
		for _, r := range a.Rules {
			ha.Rules = append(ha.Rules, helmRule{APIGroups: r.APIGroups, Resources: r.Resources, Verbs: r.Verbs})
		}
		data.Addons = append(data.Addons, ha)
	}
	b, err := yaml.Marshal(data)
	if err != nil {
		// data is a fixed, always-marshalable shape.
		panic(err)
	}
	return append([]byte(generatedByComment), b...)
}

func renderDocs(addons []AddonRBAC) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Addon adapter RBAC\n\n")
	buf.WriteString(generatedByMarkdown)
	buf.WriteString(`
Fathom runs each addon adapter under its **own least-privilege ServiceAccount**.
At reconcile time the operator builds a client that *impersonates* the addon's
ServiceAccount and hands it to the adapter, so an adapter can read exactly — and
only — what it declares below. The operator ServiceAccount itself holds **no
addon read permissions**; it holds only ` + "`impersonate`" + ` on these
per-addon ServiceAccounts (see [Operator impersonation grant](#operator-impersonation-grant)).

Each adapter declares its grants in Go (` + "`adapter.RBACDeclarer`" + `); this
page and the manifests under ` + "`config/rbac/addons/`" + ` are generated from
those declarations. Every verb is read-only (` + "`get`/`list`/`watch`" + `)
unless a **Write reason** justifies it — the read-only CI guard fails any
unjustified write.

`)
	for _, a := range addons {
		fmt.Fprintf(&buf, "## %s\n\n", a.Addon)
		fmt.Fprintf(&buf, "ServiceAccount: `fathom-%s` (namespace `fathom-system`)\n\n", a.ServiceAccount)
		buf.WriteString("| API group | Resources | Verbs | Write reason |\n")
		buf.WriteString("| --- | --- | --- | --- |\n")
		for _, r := range a.Rules {
			reason := r.WriteReason
			if reason == "" {
				reason = "—"
			}
			fmt.Fprintf(&buf, "| %s | %s | %s | %s |\n",
				groupsCell(r.APIGroups), strings.Join(r.Resources, ", "), strings.Join(r.Verbs, ", "), reason)
		}
		buf.WriteString("\n")
	}
	buf.WriteString("## Operator impersonation grant\n\n")
	buf.WriteString("The operator ServiceAccount (`fathom-controller-manager`) holds only " +
		"`impersonate` on the per-addon ServiceAccounts above, via the namespaced " +
		"Role `fathom-addon-impersonator` in `fathom-system`. It carries no addon " +
		"read permissions of its own, so each addon's blast radius is exactly its " +
		"declared rules.\n")
	return buf.Bytes()
}

// groupsCell renders an apiGroups slice for the docs table, showing the core
// group (empty string) as "core".
func groupsCell(groups []string) string {
	out := make([]string, len(groups))
	for i, g := range groups {
		if g == "" {
			out[i] = "core"
		} else {
			out[i] = g
		}
	}
	return strings.Join(out, ", ")
}
