/*
SPDX-FileCopyrightText: 2026 Rillan AI LLC
SPDX-License-Identifier: MIT
*/

package rbacgen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	api "github.com/skaphos/fathom/api/v1alpha1"
	definitions "github.com/skaphos/fathom/pkg/addondefinition"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"github.com/skaphos/fathom/pkg/adapter"
)

// WriteRuntimeInventory exposes compiled-in names without making the CLI import
// operator registration or evaluator implementations.
func WriteRuntimeInventory(root string, adapters []adapter.Adapter) error {
	var buf bytes.Buffer
	buf.WriteString("/*\nSPDX-FileCopyrightText: 2026 Rillan AI LLC\nSPDX-License-Identifier: MIT\n*/\n\n// Package addondefinition holds validated runtime definition contracts and the built-in collision inventory.\n// Code generated by task gen:runtime-definitions. DO NOT EDIT.\npackage addondefinition\n\n// BuiltinNames returns this release's collision inventory.\nfunc BuiltinNames() []string { return []string{\n")
	for _, entry := range Collect(adapters) {
		fmt.Fprintf(&buf, "%q,\n", entry.Addon)
	}
	buf.WriteString("} }\n")
	data, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(root, "pkg/addondefinition/inventory_generated.go"), data, 0644)
}

func runtimeSampleChecks() []api.DefinitionCheck {
	ns := api.DefinitionTarget{Scope: "Namespaced", Namespaces: []api.DefinitionDNSLabel{"default"}}
	cluster := api.DefinitionTarget{Scope: "Cluster"}
	return []api.DefinitionCheck{
		{Name: "workload", Kind: "Workload", Workload: &api.DefinitionWorkload{Target: ns, Kind: "Deployment", DefaultName: "controller"}},
		{Name: "crd", Kind: "CRD", CRD: &api.DefinitionCRD{Target: cluster, Names: []api.DefinitionResourceName{"widgets.example.org"}, SupportedVersions: []api.DefinitionToken{"v1"}}},
		{Name: "condition", Kind: "Condition", Condition: &api.DefinitionCondition{Target: cluster, APIVersion: "apiregistration.k8s.io/v1", Kind: "APIService", Names: []api.DefinitionResourceName{"v1.metrics.k8s.io"}, ConditionType: "Available", ExpectedStatus: "True"}},
		{Name: "field", Kind: "Field", Field: &api.DefinitionField{Target: ns, APIVersion: "example.org/v1", Kind: "Widget", ListKind: "WidgetList", FieldPath: []string{"status", "state"}, ExpectedValue: "Ready"}},
		{Name: "webhook", Kind: "Webhook", Webhook: &api.DefinitionWebhook{Target: cluster, Kind: "ValidatingWebhookConfiguration", Name: "validation"}},
		{Name: "cronjob", Kind: "CronJob", CronJob: &api.DefinitionCronJob{Target: ns, DefaultName: "job"}},
		{Name: "configmap", Kind: "ConfigMap", ConfigMap: &api.DefinitionConfigMap{Target: ns, DefaultName: "config", Key: "policy.yaml"}},
		{Name: "annotation", Kind: "AnnotationStaleness", AnnotationStaleness: &api.DefinitionAnnotationStaleness{Target: ns, APIVersion: "v1", Kind: "ConfigMap", DefaultName: "config", AnnotationKey: "example.org/last-check", DefaultMaxAge: "1m"}},
		{Name: "projection", Kind: "PodProjection", PodProjection: &api.DefinitionPodProjection{Target: ns, Selector: map[string]api.DefinitionSelectorValue{"app": "custom"}, VolumeName: "token"}},
	}
}

// WriteRuntimeSamples emits one validated non-built-in example per evaluator kind.
func WriteRuntimeSamples(root string) error {
	dir := filepath.Join(root, "config/samples/addondefinition")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	for _, check := range runtimeSampleChecks() {
		name := "example-" + strings.ToLower(check.Kind)
		d := &api.AddonDefinition{TypeMeta: metav1.TypeMeta{APIVersion: api.GroupVersion.String(), Kind: "AddonDefinition"}, ObjectMeta: metav1.ObjectMeta{Name: name}, Spec: api.AddonDefinitionSpec{AddonType: api.DefinitionDNSLabel(name), AdapterVersion: "1.0.0", SemanticsVersion: 1, Families: []api.DefinitionFamily{{Name: "health", Checks: []api.DefinitionCheck{check}}}}}
		if err := definitions.Validate(d); err != nil {
			return err
		}
		data, err := yaml.Marshal(d)
		if err != nil {
			return err
		}
		header := "# SPDX-FileCopyrightText: 2026 Rillan AI LLC\n# SPDX-License-Identifier: MIT\n# Generated by task gen:runtime-definitions. DO NOT EDIT.\n"
		if err := os.WriteFile(filepath.Join(dir, strings.ToLower(check.Kind)+".yaml"), append([]byte(header), data...), 0644); err != nil {
			return err
		}
	}
	return nil
}
