/*
SPDX-FileCopyrightText: 2026 Rillan AI LLC
SPDX-License-Identifier: MIT
*/

// Code generated by task gen:runtime-definitions. DO NOT EDIT.
package addondefinition

// BuiltinNames returns this release's collision inventory.
func BuiltinNames() []string {
	return []string{
		"argocd",
		"azure-workload-identity",
		"cert-manager",
		"cilium",
		"coredns",
		"descheduler",
		"envoy-gateway",
		"external-dns",
		"external-secrets",
		"istio",
		"keda",
		"kube-state-metrics",
		"kured",
		"metrics-server",
		"node-local-dns",
		"vpa",
	}
}
