apiVersion: fathom.skaphos.io/v1alpha1
kind: HealthCheck
metadata:
  labels:
    app.kubernetes.io/name: fathom
    app.kubernetes.io/managed-by: kustomize
  name: healthcheck-sample
spec:
  # TODO(user): Add fields here
