## Append samples of your project ##
resources:
- fathom_v1alpha1_addoncheck.yaml
- fathom_v1alpha1_addoncheck_coredns.yaml
- fathom_v1alpha1_addoncheck_external_secrets.yaml
- fathom_v1alpha1_addoncheck_cilium.yaml
- fathom_v1alpha1_healthcheck.yaml
- fathom_v1alpha1_clusterhealth.yaml
- fathom_v1alpha1_healthreport.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
