/*
SPDX-FileCopyrightText: 2026 Skaphos
SPDX-License-Identifier: MIT
*/

package v1alpha1

import (
	"reflect"
	"testing"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/utils/ptr"
)

// The DeepCopy methods on every type in this package are generated by
// controller-gen (zz_generated.deepcopy.go) and are not hand-edited. These
// tests exist not to validate the generator's logic but to lock the
// generated code's contract — every type that has +kubebuilder:object on
// it must produce an independent deep copy of every nested slice, map,
// and pointer field, so that mutating the copy never mutates the
// original. Without this coverage, a missing +k8s:deepcopy-gen tag or a
// generator regression goes silently unnoticed.

// fullyPopulatedAddonCheck returns an AddonCheck with every optional
// slice/map/pointer field non-nil so the generated DeepCopy exercises
// every branch (not just the nil-fast-path).
func fullyPopulatedAddonCheck() *AddonCheck {
	interval := metav1.Duration{Duration: 5 * time.Minute}
	timeout := metav1.Duration{Duration: 30 * time.Second}
	historyLimit := int32(10)
	lastRun := metav1.NewTime(time.Unix(1_700_000_000, 0))
	return &AddonCheck{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "AddonCheck"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "sample",
			Namespace: "default",
			Labels:    map[string]string{"k": "v"},
		},
		Spec: AddonCheckSpec{
			AddonType:    "cert-manager",
			Interval:     &interval,
			Timeout:      &timeout,
			HistoryLimit: &historyLimit,
			Paused:       false,
			Policy: map[string]AddonCheckFamilyPolicy{
				"system_health": {
					Enabled:    ptr.To(true),
					Namespaces: []string{"cert-manager"},
					LabelSelector: &metav1.LabelSelector{
						MatchLabels: map[string]string{"app": "cert-manager"},
						MatchExpressions: []metav1.LabelSelectorRequirement{{
							Key:      "tier",
							Operator: metav1.LabelSelectorOpIn,
							Values:   []string{"control-plane"},
						}},
					},
					Thresholds: map[string]string{"restartWarnCount": "3"},
				},
			},
		},
		Status: AddonCheckStatus{
			Conditions: []metav1.Condition{{
				Type:               "Ready",
				Status:             metav1.ConditionTrue,
				LastTransitionTime: lastRun,
				Reason:             "RunCompleted",
				Message:            "ok",
			}},
			LastRunTime:    &lastRun,
			LastReportName: "sample-abc12",
			LastResult:     "Pass",
		},
	}
}

func fullyPopulatedClusterHealth() *ClusterHealth {
	observedAt := metav1.NewTime(time.Unix(1_700_000_100, 0))
	return &ClusterHealth{
		TypeMeta:   metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "ClusterHealth"},
		ObjectMeta: metav1.ObjectMeta{Name: "cluster"},
		Spec: ClusterHealthSpec{
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{"managed-by": "fathom"},
			},
		},
		Status: ClusterHealthStatus{
			Conditions: []metav1.Condition{{
				Type:               "Ready",
				Status:             metav1.ConditionTrue,
				LastTransitionTime: observedAt,
			}},
			Children: []ClusterHealthChildSummary{{
				Name:       "coredns-sample",
				Result:     "Pass",
				Summary:    "ok",
				ObservedAt: &observedAt,
			}},
			ObservedAt: &observedAt,
			Result:     "Pass",
		},
	}
}

func fullyPopulatedHealthCheck() *HealthCheck {
	observedAt := metav1.NewTime(time.Unix(1_700_000_200, 0))
	return &HealthCheck{
		TypeMeta:   metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "HealthCheck"},
		ObjectMeta: metav1.ObjectMeta{Name: "coredns-sample"},
		Spec: HealthCheckSpec{
			CheckRef: CheckTargetRef{
				APIVersion: "fathom.skaphos.io/v1alpha1",
				Kind:       "AddonCheck",
				Namespace:  "default",
				Name:       "coredns-sample",
			},
			Description: "DNS reachability",
		},
		Status: HealthCheckStatus{
			Conditions: []metav1.Condition{{
				Type:               "Ready",
				Status:             metav1.ConditionTrue,
				LastTransitionTime: observedAt,
			}},
			SourceObservedAt: &observedAt,
			Result:           "Pass",
		},
	}
}

func fullyPopulatedHealthReport() *HealthReport {
	observedAt := metav1.NewTime(time.Unix(1_700_000_300, 0))
	duration := metav1.Duration{Duration: 250 * time.Millisecond}
	checkDuration := metav1.Duration{Duration: 25 * time.Millisecond}
	return &HealthReport{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "HealthReport"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "coredns-sample-abc12",
			Namespace: "default",
			Labels: map[string]string{
				"fathom.skaphos.io/source-name": "coredns-sample",
				"fathom.skaphos.io/source-kind": "AddonCheck",
			},
		},
		Spec: HealthReportSpec{
			SourceRef: HealthReportTargetRef{
				APIVersion: "fathom.skaphos.io/v1alpha1",
				Kind:       "AddonCheck",
				Namespace:  "default",
				Name:       "coredns-sample",
			},
			AddonType:       "coredns",
			AdapterName:     "coredns",
			AdapterVersion:  "0.1.0",
			ContractVersion: "0.2.0",
			Result:          HealthReportResultPass,
			Checks: []HealthReportCheck{{
				Family:  "dns_resolution",
				Result:  HealthReportResultPass,
				Summary: "DNS resolution succeeded",
				Details: map[string]string{
					"latencyMillis": "25",
					"target":        "kubernetes.default.svc.cluster.local",
				},
				ObservedAt: observedAt,
				Duration:   &checkDuration,
				TargetRef: HealthReportTargetRef{
					Kind: "DNSName",
					Name: "kubernetes.default.svc.cluster.local",
				},
			}},
			ObservedAt: observedAt,
			Duration:   &duration,
		},
	}
}

// deepCopyContract asserts the three guarantees DeepCopy is supposed to
// provide: non-nil result, distinct pointer, structural equality.
//
// Zero-sized struct pointers are exempt from the distinct-pointer check
// because Go's runtime is free to alias them — `new(struct{})` may return
// the same address across calls. Structural equality is still asserted.
func deepCopyContract(t *testing.T, name string, original, copy any) {
	t.Helper()
	cv := reflect.ValueOf(copy)
	if cv.IsNil() {
		t.Fatalf("%s.DeepCopy: returned nil", name)
	}
	if cv.Type().Elem().Size() > 0 &&
		reflect.ValueOf(original).Pointer() == cv.Pointer() {
		t.Fatalf("%s.DeepCopy: returned same pointer as input", name)
	}
	if !reflect.DeepEqual(original, copy) {
		t.Fatalf("%s.DeepCopy: structural inequality between original and copy", name)
	}
}

// runtimeObjectContract asserts DeepCopyObject returns a non-nil distinct
// runtime.Object whose dynamic type matches the original. Only types with
// +kubebuilder:object:root=true implement runtime.Object.
func runtimeObjectContract(t *testing.T, name string, original runtime.Object) {
	t.Helper()
	copy := original.DeepCopyObject()
	if copy == nil {
		t.Fatalf("%s.DeepCopyObject: returned nil", name)
	}
	if reflect.TypeOf(original) != reflect.TypeOf(copy) {
		t.Fatalf("%s.DeepCopyObject: type mismatch %T vs %T", name, original, copy)
	}
}

func TestDeepCopy_AddonCheck(t *testing.T) {
	orig := fullyPopulatedAddonCheck()
	copy := orig.DeepCopy()
	deepCopyContract(t, "AddonCheck", orig, copy)

	// Independence: mutate the copy, original must stay unchanged.
	copy.Spec.Policy["system_health"].Thresholds["restartWarnCount"] = "99"
	if orig.Spec.Policy["system_health"].Thresholds["restartWarnCount"] == "99" {
		t.Fatal("AddonCheck.DeepCopy: nested map share detected (mutation leaked)")
	}

	runtimeObjectContract(t, "AddonCheck", orig)
}

func TestDeepCopy_AddonCheckList(t *testing.T) {
	orig := &AddonCheckList{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "AddonCheckList"},
		Items:    []AddonCheck{*fullyPopulatedAddonCheck()},
	}
	copy := orig.DeepCopy()
	deepCopyContract(t, "AddonCheckList", orig, copy)

	copy.Items[0].Spec.AddonType = "mutated"
	if orig.Items[0].Spec.AddonType == "mutated" {
		t.Fatal("AddonCheckList.DeepCopy: Items slice share detected")
	}

	runtimeObjectContract(t, "AddonCheckList", orig)
}

func TestDeepCopy_ClusterHealth(t *testing.T) {
	orig := fullyPopulatedClusterHealth()
	copy := orig.DeepCopy()
	deepCopyContract(t, "ClusterHealth", orig, copy)

	copy.Status.Children[0].Name = "mutated"
	if orig.Status.Children[0].Name == "mutated" {
		t.Fatal("ClusterHealth.DeepCopy: Children slice share detected")
	}

	runtimeObjectContract(t, "ClusterHealth", orig)
}

func TestDeepCopy_ClusterHealthList(t *testing.T) {
	orig := &ClusterHealthList{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "ClusterHealthList"},
		Items:    []ClusterHealth{*fullyPopulatedClusterHealth()},
	}
	copy := orig.DeepCopy()
	deepCopyContract(t, "ClusterHealthList", orig, copy)
	runtimeObjectContract(t, "ClusterHealthList", orig)
}

func TestDeepCopy_HealthCheck(t *testing.T) {
	orig := fullyPopulatedHealthCheck()
	copy := orig.DeepCopy()
	deepCopyContract(t, "HealthCheck", orig, copy)

	copy.Spec.CheckRef.Name = "mutated"
	if orig.Spec.CheckRef.Name == "mutated" {
		t.Fatal("HealthCheck.DeepCopy: CheckRef share detected")
	}

	runtimeObjectContract(t, "HealthCheck", orig)
}

func TestDeepCopy_HealthCheckList(t *testing.T) {
	orig := &HealthCheckList{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "HealthCheckList"},
		Items:    []HealthCheck{*fullyPopulatedHealthCheck()},
	}
	copy := orig.DeepCopy()
	deepCopyContract(t, "HealthCheckList", orig, copy)
	runtimeObjectContract(t, "HealthCheckList", orig)
}

func TestDeepCopy_HealthReport(t *testing.T) {
	orig := fullyPopulatedHealthReport()
	copy := orig.DeepCopy()
	deepCopyContract(t, "HealthReport", orig, copy)

	copy.Spec.Checks[0].Details["latencyMillis"] = "9999"
	if orig.Spec.Checks[0].Details["latencyMillis"] == "9999" {
		t.Fatal("HealthReport.DeepCopy: nested Checks.Details map share detected")
	}

	runtimeObjectContract(t, "HealthReport", orig)
}

func TestDeepCopy_HealthReportList(t *testing.T) {
	orig := &HealthReportList{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "HealthReportList"},
		Items:    []HealthReport{*fullyPopulatedHealthReport()},
	}
	copy := orig.DeepCopy()
	deepCopyContract(t, "HealthReportList", orig, copy)
	runtimeObjectContract(t, "HealthReportList", orig)
}

// fullyPopulatedNodeCertificateCheck returns a NodeCertificateCheck with every
// optional slice/map/pointer field non-nil so the generated DeepCopy exercises
// every branch (notably the corev1.Toleration slice and the threshold pointers).
func fullyPopulatedNodeCertificateCheck() *NodeCertificateCheck {
	warn := int32(30)
	critical := int32(7)
	interval := metav1.Duration{Duration: time.Hour}
	timeout := metav1.Duration{Duration: 30 * time.Second}
	historyLimit := int32(10)
	lastRun := metav1.NewTime(time.Unix(1_700_000_200, 0))
	return &NodeCertificateCheck{
		TypeMeta:   metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "NodeCertificateCheck"},
		ObjectMeta: metav1.ObjectMeta{Name: "node-certs", Namespace: "fathom-system"},
		Spec: NodeCertificateCheckSpec{
			Paths:        []string{"/etc/kubernetes/pki", "/etc/kubernetes/admin.conf"},
			WarnDays:     &warn,
			CriticalDays: &critical,
			NodeSelector: map[string]string{"kubernetes.io/os": "linux"},
			Tolerations: []corev1.Toleration{{
				Key:      "node-role.kubernetes.io/control-plane",
				Operator: corev1.TolerationOpExists,
				Effect:   corev1.TaintEffectNoSchedule,
			}},
			Interval:     &interval,
			Timeout:      &timeout,
			HistoryLimit: &historyLimit,
		},
		Status: NodeCertificateCheckStatus{
			Conditions: []metav1.Condition{{
				Type:               "Ready",
				Status:             metav1.ConditionTrue,
				LastTransitionTime: lastRun,
				Reason:             "Reporting",
			}},
			LastRunTime:    &lastRun,
			LastResult:     "Warn",
			LastReportName: "node-certs-abc12",
			DesiredNodes:   3,
			ReportingNodes: 3,
		},
	}
}

func TestDeepCopy_NodeCertificateCheck(t *testing.T) {
	orig := fullyPopulatedNodeCertificateCheck()
	copy := orig.DeepCopy()
	deepCopyContract(t, "NodeCertificateCheck", orig, copy)

	copy.Spec.NodeSelector["kubernetes.io/os"] = "windows"
	if orig.Spec.NodeSelector["kubernetes.io/os"] == "windows" {
		t.Fatal("NodeCertificateCheck.DeepCopy: nested NodeSelector map share detected")
	}
	copy.Spec.Tolerations[0].Key = "mutated"
	if orig.Spec.Tolerations[0].Key == "mutated" {
		t.Fatal("NodeCertificateCheck.DeepCopy: Tolerations slice share detected")
	}

	runtimeObjectContract(t, "NodeCertificateCheck", orig)
}

func TestDeepCopy_NodeCertificateCheckList(t *testing.T) {
	orig := &NodeCertificateCheckList{
		TypeMeta: metav1.TypeMeta{APIVersion: GroupVersion.String(), Kind: "NodeCertificateCheckList"},
		Items:    []NodeCertificateCheck{*fullyPopulatedNodeCertificateCheck()},
	}
	copy := orig.DeepCopy()
	deepCopyContract(t, "NodeCertificateCheckList", orig, copy)

	copy.Items[0].Spec.Paths[0] = "mutated"
	if orig.Items[0].Spec.Paths[0] == "mutated" {
		t.Fatal("NodeCertificateCheckList.DeepCopy: Items slice share detected")
	}

	runtimeObjectContract(t, "NodeCertificateCheckList", orig)
}

// TestDeepCopy_LeafTypesDirect covers the leaf helper types whose DeepCopy
// methods aren't reached by the resource-level tests above because their
// parents copy them by value (struct memcpy) rather than recursing into
// the generated DeepCopyInto. controller-gen still emits DeepCopy for
// every +k8s:deepcopy-gen struct, so they need direct exercise to count
// against the package coverage.
func TestDeepCopy_LeafTypesDirect(t *testing.T) {
	tests := []struct {
		name string
		do   func(t *testing.T)
	}{
		{
			name: "CheckTargetRef",
			do: func(t *testing.T) {
				orig := &CheckTargetRef{APIVersion: "v1", Kind: "Pod", Namespace: "default", Name: "x"}
				deepCopyContract(t, "CheckTargetRef", orig, orig.DeepCopy())
			},
		},
		{
			name: "ClusterHealthChildSummary",
			do: func(t *testing.T) {
				now := metav1.NewTime(time.Unix(1_700_000_000, 0))
				orig := &ClusterHealthChildSummary{
					Name: "x", Result: "Pass", Summary: "ok", ObservedAt: &now,
				}
				deepCopyContract(t, "ClusterHealthChildSummary", orig, orig.DeepCopy())
			},
		},
		{
			name: "HealthReportCheck",
			do: func(t *testing.T) {
				now := metav1.NewTime(time.Unix(1_700_000_000, 0))
				dur := metav1.Duration{Duration: 5 * time.Millisecond}
				orig := &HealthReportCheck{
					Family:     "system_health",
					Result:     HealthReportResultPass,
					TargetRef:  HealthReportTargetRef{Kind: "Pod", Name: "x"},
					Summary:    "ok",
					Details:    map[string]string{"k": "v"},
					ObservedAt: now,
					Duration:   &dur,
				}
				deepCopyContract(t, "HealthReportCheck", orig, orig.DeepCopy())
			},
		},
		{
			name: "HealthReportTargetRef",
			do: func(t *testing.T) {
				orig := &HealthReportTargetRef{APIVersion: "v1", Kind: "Pod", Name: "x"}
				deepCopyContract(t, "HealthReportTargetRef", orig, orig.DeepCopy())
			},
		},
		{
			name: "HealthReportStatus",
			do: func(t *testing.T) {
				orig := &HealthReportStatus{}
				deepCopyContract(t, "HealthReportStatus", orig, orig.DeepCopy())
			},
		},
		{
			name: "AddonCheckFamilyPolicy",
			do: func(t *testing.T) {
				orig := &AddonCheckFamilyPolicy{
					Enabled:    ptr.To(true),
					Namespaces: []string{"default"},
					LabelSelector: &metav1.LabelSelector{
						MatchLabels: map[string]string{"app": "x"},
					},
					Thresholds: map[string]string{"k": "v"},
				}
				deepCopyContract(t, "AddonCheckFamilyPolicy", orig, orig.DeepCopy())
			},
		},
		{
			name: "AddonCheckSpec",
			do: func(t *testing.T) {
				deepCopyContract(t, "AddonCheckSpec",
					&fullyPopulatedAddonCheck().Spec,
					fullyPopulatedAddonCheck().Spec.DeepCopy())
			},
		},
		{
			name: "AddonCheckStatus",
			do: func(t *testing.T) {
				deepCopyContract(t, "AddonCheckStatus",
					&fullyPopulatedAddonCheck().Status,
					fullyPopulatedAddonCheck().Status.DeepCopy())
			},
		},
		{
			name: "ClusterHealthSpec",
			do: func(t *testing.T) {
				deepCopyContract(t, "ClusterHealthSpec",
					&fullyPopulatedClusterHealth().Spec,
					fullyPopulatedClusterHealth().Spec.DeepCopy())
			},
		},
		{
			name: "ClusterHealthStatus",
			do: func(t *testing.T) {
				deepCopyContract(t, "ClusterHealthStatus",
					&fullyPopulatedClusterHealth().Status,
					fullyPopulatedClusterHealth().Status.DeepCopy())
			},
		},
		{
			name: "HealthCheckSpec",
			do: func(t *testing.T) {
				deepCopyContract(t, "HealthCheckSpec",
					&fullyPopulatedHealthCheck().Spec,
					fullyPopulatedHealthCheck().Spec.DeepCopy())
			},
		},
		{
			name: "HealthCheckStatus",
			do: func(t *testing.T) {
				deepCopyContract(t, "HealthCheckStatus",
					&fullyPopulatedHealthCheck().Status,
					fullyPopulatedHealthCheck().Status.DeepCopy())
			},
		},
		{
			name: "HealthReportSpec",
			do: func(t *testing.T) {
				deepCopyContract(t, "HealthReportSpec",
					&fullyPopulatedHealthReport().Spec,
					fullyPopulatedHealthReport().Spec.DeepCopy())
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, tc.do)
	}
}
